// app/layout.js
import Providers from "./providers"; // Import our new wrapper

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Wrap your children here instead */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}